server:
  port: 8080
spring:
  application:
    name: core
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000
    redisson:
      config:
        # file: classpath:redisson.yml
        singleServerConfig:
          # 数据库编号
          database: 0
          # 节点地址
          address: redis://127.0.0.1:6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    # ziji peizhi
    enabled: true
    exchangeName: cores-user-exhcange-direct
    userQueueName: cores-user-queue-userList
    userRoutingKey: cores-user-queue-userList
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #hikari数据源特性配置
    hikari:
      maximum-pool-size: 100 #最大连接数,默认值10.
      minimum-idle: 20 #最小空闲连接，默认值10.
      connection-timeout: 60000 #连接超时时间(毫秒),默认值30秒.
      #空闲连接超时时间，默认值600000(10分钟),只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      #如果大于等于 max-lifetime 且 max-lifetime>0,则会被重置为0.
      idle-timeout: 600000
      max-lifetime: 3000000 #连接最大存活时间,默认值30分钟.设置应该比mysql设置的超时时间短
mybatis-plus:
  # 指定 Mapper XML 文件的位置，使用 classpath 通配符指定路径
  mapper-locations: classpath:/mappers/*.xml
  # 指定实体类的包路径，用于自动扫描并注册类型别名
  type-aliases-package: com.zd.core.*
  global-config:
    db-config:
      id-type: input
      # 驼峰下划线转换（将数据库字段的下划线命名规则转换为 Java 实体类属性的驼峰命名规则）
      db-column-underline: true
      # 刷新 mapper
      refresh-mapper: true
  configuration:
    # 将 Java 实体类属性的驼峰命名规则转换为数据库字段的下划线命名规则
    map-underscore-to-camel-case: true
    # 查询结果中包含空值的列，在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 开启 sql 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 无法使用的服务
sftp:
  host: 192.168.1.4
  port: 21
  username: administrator
  password: 1
  uploadFileDir: C://Users//Administrator//Desktop//ftp
  downloadFileBasePath: https://mf-seller-static-pre-release-hk.orangeconnex.com
  templateDir: C://Users//Administrator//Desktop//ftp//templates